  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

    [build]
  # Directory to change to before starting a build
  base = "client" # Adjust this if your frontend code is in a different directory

  # Build command
  command = "npm run build"

  # Directory to publish (relative to the base directory)
  publish = "build" # Adjust this to match your build output directory

[build.environment]
  # Define environment variables here
  REACT_APP_API_KEY = "your_api_key"
