# Redirects configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build configuration
[build]
  # Directory to change to before starting a build
  base = "client" # Adjust this if your frontend code is in a different directory
  command = "npm run build"
  publish = "build"
  functions = "functions"

  [build.environment]
    # Define environment variables here
    REACT_APP_API_KEY = "https://unicoderr-projectmanagement.netlify.app/"
